### PR TITLE
Improve nightlies and add cvc4

### LINKED ISSUE #699: Solver configuration in CI
Right now the cryptol test suite appears only to exercise symbolic solving via Z3.  It would be nice to test other solvers in the test suite (e.g., CVC4, yices).

Currently the travis build for cryptol just `curl`s a pretty old copy of Z3 from `saw.galois.com`, which seems suboptimal.  I believe `fryingpan` builds can install other solvers, but I don't know how to set that up.  @kquick, any thoughts on the best way to handle this?

### LINKED ISSUE #750: Github Actions and Travis builds need CVC4
The Cryptol test suite now uses CVC4 in one of its tests.  Some (but not all) of the CI checks for this repository need to be updated to include a recent CVC4 to make the test suite go green.

### PR DESCRIPTION
**Pull request by jared-w**
- nightlies should now have better names
- nightlies now include docs and should be pretty much a normal full release, just without signing.
- I cleaned up the yaml files slightly to have less bash code in the outputs
- scheduled runs are now testable without annoyingness :)
- I removed the artifact cleaner-upper. We can revisit that should we actually need it in the future
- The matrix no longer fails fast.
- cvc4 is also enabled for macos.
- I'm temporarily using the haskell-CI/setup fork of actions/setup-haskell to get around a bug that was causing macOS builds to fail.

closes #699 
closes #750

### CODE REVIEW

**Comment by jared-w** [comment]
Windows is currently quite flaky on ghc 8.8+. This is a known thing, and there's not a whole lot we can do about it currently until ghc 8.8.4 and 8.10.2 comes out.

**Comment by robdockins** [comment]
Thanks for working on this @jared-w !  Seems like we're in much better shape than before.  Would it be possible to mark the Windows builds as optional or something while they're still flaky? It's annoying to get build failure email notifications for build problems I can't do anything about.

**Comment by atomb** [comment]
Yeah, I wonder if it makes sense to just disable the (Windows x GHC 8.8.3) element of the build matrix for now, as that seems like the really flaky one.

**Comment by jared-w** [comment]
I can certainly disable the windows ghc 8.8.3 one specifically and wait for 8.8.4 to come out (hopefully soon).

**Comment by atomb** [comment]
Yeah, let's do that for now. And for the builds that use only one GHC version, let's just use whichever is currently most reliable (8.6.5 maybe?).

**Pull request merged**
