### PR TITLE
Specialize types of signed div/mod operators (/$) and (%$) to bitvectors

### PR DESCRIPTION
**Pull request by brianhuffman**
We discussed this idea in the thread for #686. This change would trivially fix issue #661.

This branch is not ready yet, as there are some other things I'd like to add:
* more tests (apparently neither `/$` nor `%$` is used in the test suite)
* improved doc-strings for `/$` and `%$` (#677)
* documentation in `CHANGELOG.md`

While I'm working on div/mod, I'd also like to add a fix for #662.

### CODE REVIEW

**Comment by robdockins** [comment]
What's your intended fix for #662? I have essentially the same issue with the What4 backend I'm working on, and trying to figure out the simplest translation.  I need to work out the details, but my hypothesis is that we get "round down" behavior from the SMTLib behavior via:

```
x / y = smtlibDivision(x , y)  when y is positive
x / y = smtlibDivision(-x, -y) when y is negative

x % y = smtlibMod( x, y )   when y is positive
x % y = smtlibMod( -x, -y ) when y is negative
```

**Comment by brianhuffman** [comment]
To fix #662, the first step is to decide once and for all what rounding behavior we *want*. If we do want "round down", then the translation you suggest will probably work just fine.

In any case, we need to have a regression test that clearly states what properties `/` is supposed to satisfy, and do some `:check` and `:prove` commands to ensure that both the concrete and symbolic backends have the right semantics.

**Comment by weaversa** [comment]
Since Integers are signed, shouldn't it be:

Bitvectors will have operators (/$), (%$), (/), and (%).
Integers will have operators (/$) and (%$).

Here we've been referring to (/$) as _signed_ division, but perhaps we really mean two's complement division. If this is the case, I'm ok with the current plan.

**Comment by brianhuffman** [comment]
That's right: I've been using the term *signed* as if it only applied to a particular interpretation of bitvectors; *two's complement* would be a more accurate name. I will ensure that the doc-strings of those operators use that terminology, and update them if necessary.

**Comment by robdockins** [comment]
Indeed, in current master we have:
```
Cryptol> :help (/$)

    (/$) : {a} (Arith a) => a -> a -> a

Precedence 90, associates to the left.

2's complement signed division.  Division rounds toward 0.
```

We always basically intended 2's complement signed division, so I think the restriction to bitvectors makes perfect sense.

**Comment by weaversa** [comment]
It bugs me that the following function will give semantically different results for Integers and bitvectors 


F : {a} (Arith a) => a -> a -> a
F a b = (b - a) % 10

**Comment by brianhuffman** [comment]
That function's behavior is perfectly consistent between `Integer` and `[n]`, as long as you don't let the subtraction underflow:
```
Cryptol> let F a b = (b - a) % 10
Cryptol> :exhaust \(a:[8]) b -> a <= b ==> F (toInteger a) (toInteger b) == toInteger (F a b)
Using exhaustive testing.
Passed 65536 tests.
Q.E.D.
```
That's about as much as you can expect. In the presence of wrap-around, div/mod on bitvectors  don't really satisfy any nice algebraic properties at all.

**Comment by weaversa** [comment]
I was recently working on a cryptol spec that needed signed mod in the above case because the subtraction did underflow. I didn’t need the spec to work on both integers and bitvectors, but it irked me none the less.

If Integers only had /$ and %$, things would be more consistent. I’m just unsure of the change. Clearly, removing / and % for Integers would be a large breaking change.

**Comment by robdockins** [comment]
Well, even if you use `(%$)` you get different results in general: both because of wrap-around behavior (10 is not a power of 2) and because of rounding direction (bitvector signed division rounds to 0, integer division rounds to neg-infinity)

**Comment by robdockins** [comment]
I took the liberty of rebasing this on top of current master

**Comment by robdockins** [comment]
Folded into #724

**Pull request closed without merging**
