### PR TITLE
Lhs indexing

### PR DESCRIPTION
**Pull request by brianhuffman**
This branch implements the feature requested in #577. It lets us write declarations of the form `xs @ i = e`, which get desugared as `xs = generate (\i -> e)`.

Before merging, we still need to deal with a problem I introduced in the parser: The changes have introduced a new shift/reduce conflict that I don't yet know how to avoid. We should fix this.

### CODE REVIEW

**Comment by brianhuffman** [comment]
Note that this patch does not yet implement lhs indexing for record constructors or field updates. So things like `{ foo @ i = i+1 }` do not work. Should we implement this before merging?

**Comment by yav** [comment]
It may be nice to to do, if you have the time, just for consistency.   You'd have to modify the production for `field_expr`.  Currently we transform a field `f x = e` into `f = \x -> e` directly in the parser.  We could do the same for indexing where `f x @i = e` becomes `f = \x -> generate (\i -> e)`.

**Comment by yav** [comment]
Could you also update `docs/Syntax.md` with some examples of the new syntax?

**Comment by brianhuffman** [comment]
829c9b9494ad073ecc5bf3dcef8355ba3fcf8d9a adds support for lhs indexing on record constructors and updates. I still need to update the documentation.

**Pull request merged**
