### PR TITLE
Exclusive enumeration

### LINKED ISSUE #973: Base case for enumerations
```
Cryptol> [1..3]
[1, 2, 3]
Cryptol> [2..3]
[2, 3]
Cryptol> [3..3]
[3]
Cryptol> [4..3]

[error] at <interactive>:1:1--1:7:
  Unsolvable constraints:
    • 3 >= 4
        arising from
        use of finite enumeration
        at <interactive>:1:1--1:7
    • Reason: It is not the case that 3 >= 4
```
I am advocating here that `[4..3]` should result in `[]` rather than an error. I'm fine if `[5..3]` gives an error, but I would like to be able to create an enumeration with no elements.

This comes from trying to create a Cryptol spec of RC2 (https://tools.ietf.org/html/rfc2268). Namely, this loop here:
```
   for i = T, T+1, ..., 127 do
     L[i] = PITABLE[L[i-1] + L[i-T]];
```
T is a type variable that ranges from 1 to 128 inclusive, and when T is 128 we don't enter the loop. It is possible to write this in Cryptol, but it's not as clean as it could be.

```
    L = K
      # [ PITABLE@(L@(i-1) + L@(i-`T))
        | i <- take [`T ... ] ] : [128][8]
```

I'd rather like to write something like:
```
    L = K
      # [ PITABLE@(L@(i-1) + L@(i-`T))
        | i <- [`T .. 127 ] ] : [128][8]
```

An alternative way to write it is like so:

```
    L = K # (drop`{T} L') : [128][8]
    L'@i = PITABLE@(L@(i-1) + L@(i-`T))
```
But even so I'd still like use the loop bounds from the spec, like so, but this doesn't work when `T = 128`:
```
    L = K # L'@@[T..127]
    L'@i = PITABLE@(L@(i-1) + L@(i-`T))
```

### LINKED ISSUE #1063: Make `generate` and lhs-indexing work for infinite sequences indexed by `Integer`.
Currently `generate`, which is used for lhs-indexing syntactic sugar, can only be used for finite lists of length at least 1:
```
Cryptol> :? generate

    generate : {n, a, ix} (fin n, n >= 1, Integral ix,
                           Literal (n - 1) ix) =>
                 (ix -> a) -> [n]a

Produce a sequence using a generating function.
Satisfies 'generate f @ i == f i' for all 'i' between '0' and 'n-1'.

Declarations of the form 'x @ i = e' are syntactic sugar for
'x = generate (\i -> e)'.
```

It would be nice if we could use it for lists of any length, specifically for infinite sequences which could be indexed by an `Integer`. Being able to define zero-length sequences would be useful too, e.g. for defining sequences that are polymorphic in the length.

Implementing this will probably require adding a new type predicate as a constraint.

### PR DESCRIPTION
**Pull request by robdockins**
Add support for enumerations with exclusive upper bounds.  This allows us to capture two different boundary conditions: empty sequences and infinite sequences.

```
Cryptol> :t [ 0:Integer .. <0 ]
[0 : Integer .. < 0] : [0]Integer
Cryptol> :t [ 0:Integer .. <inf ]
[0 : Integer .. < inf] : [inf]Integer
```

As a result, we can redefine `generate` in a way that allows LHS indexing to likewise produce infinite and empty sequences

```
generate : {n, a, ix} (Integral ix, LiteralLessThan n ix) => (ix -> a) -> [n]a
generate f = [ f i | i <- [0 .. <n] ]
```

Fixes #1063
Fixes #973

There are still some questions we need to answer regarding #1062.

### CODE REVIEW

**Comment by weaversa** [comment]
@robdockins #973 contains a good suggestion by you about setting the stride. Are you planning to tackle that here as well?

**Comment by robdockins** [comment]
I haven't thought about it much since I made that suggestion.  Is that something you think people would find useful?

**Comment by weaversa** [comment]
Yes, and I didn't want to comment to disappear -- I see this PR is labeled "Fixes #973". Would you be willing to capture your idea in a new issue?

**Comment by robdockins** [comment]
CF #1087

**Review by brianhuffman — APPROVED** [review]

**Pull request merged**
