### PR TITLE
Add a ':write' command

### PR DESCRIPTION
**Pull request by TomMD**
This pull addresses issue #216 by allowing users to write out bytes (`fin n => [n][8]`) via `:write filename expression`.

I'd appreciate someone (anyone, @acfoltzer ?) else glancing at this.  Certainly any functionality issue should be raised but I'm more concerned about getting a useful API so no one feels like this is half-done.

@yav suggested a `Binary` instance to allow serialization of all sensible Cryptol types into some format, or a hex serialization of `[n]`.  Such a design would satisfy any user who can munge data post-Cryptol but I wanted to avoid making any format implicit in `:write` (including endian-ness).  Certainly yav's comments don't preclude my use case, but I feel what is currently implemented meets the majority of interesting uses.  Other opinions welcome, but I am using this version of `:write` in IRAD and would appreciate either a merge thumbs up or unambiguous requirement for merging.

----

The intent here is to allow users to write expressions to disk without
copy and pasting the ASCII representation into some other system (ex: a
Haskell script) to perform the actual file write.

Use:

```
Cryptol> :write /tmp/foo "hello Cryptol!\n"
Cryptol> :!cat /tmp/foo
hello Cryptol!
Cryptol> let var = "Complex computation\n"
Cryptol> :write /tmp/foo var
Cryptol> :!cat /tmp/foo
Complex computation
Cryptol> let var = 32 : [32]
Cryptol> :write /tmp/foo var
Can not write expression of types other than [n][8].  Type was:  [32]
```

### CODE REVIEW

**Comment by acfoltzer** [comment]
This looks quite good. Given the discussion above, maybe we could change `:read` and `:write` to `:readByteArray` and `:writeByteArray` or similar, leaving the more generic names open for if/when we decide to make serialization work for more complex types. Also, a test case or two would be great; something involving roundtripping, something involving putting a KAT in a file, etc?

**Comment by TomMD** [comment]
@acfoltzer   Merged in the latest, fixed merge issues, renamed to read/writeByteArray, added a test write/read/==.  I think this is in a reasonably good state now.

**Comment by TomMD** [comment]
Now with ~ and quoted filepath support.

**Comment by TomMD** [comment]
Merge issues fixed (again).  IMO it should be merged before they diverge again.

**Comment by acfoltzer** [comment]
Thanks!

**Pull request merged**
