### PR TITLE
Command to dump generated tests

### PR DESCRIPTION
**Pull request by david-christiansen**
Here's a REPL command to dump generated tests instead of running them, so that they can be consumed by other tools.

I have a couple of questions, pre-merge:

1. The docs for this command are longer than the others due to describing its interaction with options. Should it be shortened, should they be lengthened, or is it OK?

2. Is there a CHANGELOG or NEWS file that I should update?

### CODE REVIEW

**Comment by yav** [comment]
I think that having a longer description is fine.  It would be nice to say what are the arguments to the command (i.e., FILE and EXPR).   I typed `:dumptests True "out.tests"` and was very confused as to why it "didn't work" :)

Other commands like `dumpArray` probably ought to say that too.

Also there is a small typo in the help doc: `noutput` -> `output.

As for question 2, I don't think we currently update any `CHANGES` file or anything.  There is the Cryptol book and `Syntax.md` that we should update when we change the language, but I am not sure that
there is any need to update either of those for this command.

**Comment by atomb** [comment]
This could be an opportunity to start a CHANGELOG file, though!

**Comment by david-christiansen** [comment]
I'm happy to start a CHANGELOG file if it's wanted.

**Comment by david-christiansen** [comment]
So I've fixed the misspelling (it was a remnant of a \n that had been deleted :-] ) and added argument metavariables to all the commands, for the sake of consistency.

**Comment by ZojaA** [comment]
Hi... Why I cannot installed cryptol from official site? Thanks for answer

**Comment by kiniry** [comment]
> Hi... Why I cannot installed cryptol from official site? Thanks for answer

We are not sure what problem you are having nor why you commented in this particular discussion for help.  File a new issue if you are still having difficulty.

**Pull request merged**
