### PR TITLE
CAST5 example

### PR DESCRIPTION
**Pull request by clinty**
advice for improvement welcome

### CODE REVIEW

**Comment by acfoltzer** [comment]
@TomMD, would you mind picking up this thread?

**Comment by TomMD** [comment]
@acfoltzer Certainly.  I think we can collapse a lot of the manually expanded rounds into a loop but in general having an example of CAST5 is great and I'm all for merging with or with out changes... maybe with a few more KATs but that'd be it.

**Comment by robdockins** [comment]
@TomMD, ping? Any reason not to just merge this?

**Comment by TomMD** [comment]
No, lets merge.

**Pull request merged**
