### PR TITLE
fix(rpc): reset TC solver on file/module load

### PR DESCRIPTION
**Pull request by pnwamk**
Some difficult to reproduce bugs regarding the RPC server hanging
(https://github.com/GaloisInc/cryptol/issues/1250) seemed to be
related to the type checker solver (Z3) hanging after periods of
extended use. I.e., a module would load/error quickly normally,
but if preceded by enough prior solver/server activity, Z3
would consistently hang. To avoid this, we can simply reset the
solver and reload the type checker prelude when the server is asked
to load a file or module. This solves the Z3 hang issues in observed
cases and requires no additional forking (which we're trying to
minimize when possible).

### CODE REVIEW

**Comment by robdockins** [comment]
Interesting... do you find that the Z3 version matters?

Either way, I wonder if this is worth trying to reduce to an issue we can file upstream?

**Comment by pnwamk** [comment]
It was with Z3 version 4.8.8 inside the docker container produced by [this Dockerfile](https://github.com/GaloisInc/cryptol/blob/1b52a351f7f1b549a6fac0fb1beb63dac7af617a/cryptol-remote-api/Dockerfile). The steps in this issue reproduce it: https://github.com/GaloisInc/cryptol/issues/1250#issuecomment-885782292

I can try bumping the version of Z3 in the Dockerfile to see if that impacts things and we can go from there w.r.t. a future issue.

**Comment by robdockins** [comment]
Yeah, I'd see if, e.g., Z3 4.8.11 makes a difference.

**Comment by weaversa** [comment]
We tried 4.8.13 today and it resolved our observable issues. It's possible that upgrading just stalls the problem. That is, imagine that the problem is that some series of push/pop is leaving too much in the z3 state, and when z3 is presented with a new type-checking problem, it becomes bogged down by previous state. Perhaps newer versions of z3 are simply faster, but may get bogged down in the future as the state continues to grow. The reset problem would fix any such leakage, if it exists.

Of course, it could simply be a bug in and old z3 and the new version just fixes it. I don't know.

**Comment by robdockins** [comment]
Interesting. I know they have been doing a lot of work on a new real/integer arithmetic solver over the last several versions, so that might be related.

I feel like it's a bit of a shame to reset the solver so often because then we have to reload the type-checking prelude... but if it prevents problems, perhaps it is worth it.

**Comment by pnwamk** [comment]
Chatted briefly with @atomb and I think these changes all things considered are worth merging: we're still miles ahead of where we used to be---i.e., we used to reinvoke the solver from scratch constantly and now use a single instance, [thanks](https://github.com/GaloisInc/cryptol/commit/6626c4d33e8a9470845c8613a83bbc91f16eae4a#diff-11c812f40d1c42d97abec1a0b704134767926169723f0952a06798bb9b63485f) @robdockins!---, and so while this is a slight step back in performance for some queries, it seems unlikely to be a bottle neck given that we're just doing it when a _new_ module/file is loaded explicitly by an RPC client, and that's going to potentially invoke quite a bit of cryptol/server computation anyway.

**Pull request merged**
