### PR TITLE
Feature/docs checking

### PR DESCRIPTION
**Pull request by benjaminselfridge**
Adds a tool to automatically check the REPL input and output in Programming Cryptol. A reasonably complete user guide is in `docs/README.md`.

To take full advantage of this tool, the manual sources need to be tweaked to use some custom commands. I started doing this in `CrashCourse.tex`, but did not complete the task.

There are a few more features we could add, but I think this is good enough to be pretty useful (caught a couple of bugs in the manual already).

### CODE REVIEW

**Review by atomb — APPROVED** [review]
This looks great!

**Review by brianhuffman — APPROVED** [review]
This is great, thanks for doing this!

**Comment by benjaminselfridge** [comment]
I don't understand the build failures. Does anyone know what's going on there?

**Comment by atomb** [comment]
I think it's some sort of spurious issue downloading external solvers. I just re-started the job to see if it fails again.

**Pull request merged**
