### PR TITLE
Implement an experimental `parmap` operation

### PR DESCRIPTION
**Pull request by robdockins**
This is semantically the same as `map` on finite sequences,
but forks a separate Haskell thread for each element of the sequence.
When the GHC runtime is instructed to use multiple OS threads,
data-parallel execution can be achieved.

CF #787

### CODE REVIEW

**Comment by robdockins** [comment]
This turned out to be easier to implement, and more reliable to use than I initially expected. I think we should include it before the next release as an experimental feature.  What do you think @atomb?

**Comment by atomb** [comment]
I'd be in favor of that. What does "experimental" mean in this case, though? Undocumented? Enabled with a particular flag? We've implemented a specific mechanism for marking things as experimental in SAW, but not (yet) in Cryptol.

**Comment by robdockins** [comment]
I'm open to ideas, but for now I just mean "experimental" in the sense that it is a feature that might substantially change or be removed in the future and that users should not rely heavily on it. I guess it's mostly an exercise in expectation management.

We could certainly implement some way to gate it with a flag or something; I don't know how difficult that would be.

**Comment by atomb** [comment]
That sounds fine to me. I just wanted to clarify. I think labeling it as experimental in the release notes will be a start.

**Pull request merged**
