### PR TITLE
Parameterize module system over filesystem access

### PR DESCRIPTION
**Pull request by david-christiansen**
This PR adds the ability for clients of Cryptol-the-library to provide their own means of accessing files on disk, as a sort of lightweight VFS. This will be used for caching multiple concurrent states in the SAW RPC interface.

### CODE REVIEW

**Comment by robdockins** [comment]
I took the liberty of rebasing this on top of current master.

**Comment by robdockins** [comment]
@david-christiansen, is it important to you to get this in before the 2.9 release?

**Comment by david-christiansen** [comment]
Thanks for the rebase! It's not massively important to have it in the release, but OTOH a merge would be nice to prevent bitrot.

What about a merge just after the release, to avoid last-minute pain for library clients?

**Comment by robdockins** [comment]
Makes sense to me

**Comment by yav** [comment]
Is the SAW RPC interface part of the next SAW release. If so, it'd make sense to merge that in before the release?

**Comment by david-christiansen** [comment]
AFAIK the RPC system is not scheduled for a concrete SAW release yet. But @atomb is the one to check with on that.

**Comment by robdockins** [comment]
Well, it's not a difficult change, and downstream PRs already exist to handle it.  I think we should probably just go ahead and merge it.

**Comment by robdockins** [comment]
Internal CI isn't entirely green on this branch, but it all seems to be for other reasons. I'll merge so we can get this into the release.

**Pull request merged**
