### PR TITLE
NoPat refactor

### LINKED ISSUE #567: Shadowing in a lambda list gives an unexpected result
Moved from:
https://github.com/GaloisInc/saw-script/issues/367

This is unexpected:
```
┏━╸┏━┓╻ ╻┏━┓╺┳╸┏━┓╻  
┃  ┣┳┛┗┳┛┣━┛ ┃ ┃ ┃┃  
┗━╸╹┗╸ ╹ ╹   ╹ ┗━┛┗━╸
version 2.6.1

Loading module Cryptol
Cryptol> :t \x x -> x : [8]
[warning] at <interactive>:1:4--1:5
    This binding for x shadows the existing binding from
    (at <interactive>:1:2--1:3, x)
(\x x -> x : [8]) : {a} [8] -> a -> [8]
```

### PR DESCRIPTION
**Pull request by robdockins**
Refactor NoPat to fix #567

### CODE REVIEW

**Review by brianhuffman — APPROVED** [review]
This looks reasonable to me.

**Review by yav — COMMENTED** [review]
I am not sure this is the right thing to do here, these are my thoughts:
  * I think there might be value in preserving the arity of functions, especially as we look more into generating code
  * it seems to me that `\x x -> e` should be an error, rather than a warning, just like `\(x,x) -> e` is an error
  * if you do think that's the right thing to do though, it looks like `Bind` now never has any parameters after `NoPat` so we should probably remove implementations for that from the following passes
  * I have a whole lot of changes to the renamer on my modules branch, and am about to start working on the type checker this week, so there's lot's of potential for merge conflicts, so we may want to hold off on simplifying the following passes for now

**Comment by robdockins** [comment]
Well, the typechecker reduces the arity of all functions to 1 already, so I don't think we're losing anything here.

As to the error situations: I'm open to the idea that these should be errors instead, but I couldn't figure out a good way to do that without doing a much larger refactoring that merges the NoPat pass directly into the Renamer.  I think that's a good idea, eventually, but I don't understand all the working pieces well enough to know how difficult that would be.

As to simplifying `Bind`: I'm starting to wonder if there are enough invariants we want to enforce here that it makes sense to have a separate AST (at least at the declarations level) for the results of the NoPat/Renamer pass (again, that's a larger refactoring, though).

**Comment by brianhuffman** [comment]
I agree that duplicate variables like `\x x -> x` should be an error, and this PR does not yet make that an error; but I also think it is a step in the right direction. As @robdockins says, doing everything properly will probably require a much bigger refactoring.

**Comment by yav** [comment]
I am fine with merging it, as it is fairly localized change.    However, we should probably do some sort of larger refactoring too---I've cleaned up a bunch of stuff in the renamer on the `submodules` branch, but there is still a bunch of duplication in various places (e.g., Parser.Names) so maybe we can start thinking on how we'd like things to be.  Maybe a good thing to consider for just after the release.

**Pull request merged**
