### PR TITLE
New monadic evaluator

### PR DESCRIPTION
**Pull request by robdockins**
Heavy refactoring of both the concrete and the symbolic evaluator.  Evaluation now occurs in the context of an 'Eval' monad.  This allows us to be more precise about Cryptol's space usage and strictness behavor.  As a result, this patch fixes a number of strictness bugs, and also improves the performance of the concrete evaluator by a modest about (~20% faster on computing AES).  This, I think, is due mostly to the new representation of sequences and the explicit memoization of sequence comprehensions.

This is a fairly big change and probably warrants code review before merging.

### CODE REVIEW

**Comment by weaversa** [comment]
What happened to issue #268? It doesn't seem to exist in github anymore.

**Comment by robdockins** [comment]
That... is extremely odd.  I don't know what happened to issue #268, it seems to have vanished.

**Comment by robdockins** [comment]
Annnd.... now they're back.  I've no idea what was going on there.

**Comment by TomMD** [comment]
@robdockins So github marked me as a bot - perhaps because I have a bot that pushes things on a regular basis.  On those grounds they disabled my account and any actions taken under it were hidden (including said issue).  It was painless to get the account reactivated and everything is back, so I'd say they're system worked beyond the initial misdiagnosis.

**Comment by robdockins** [comment]
It is worth noting here that the `examples/SHA1.cry` example suffers from a significant performance regression with the new evaluator.  I'm looking into the causes.

**Comment by brianhuffman** [comment]
The new evaluator's blackhole detection is a bit overzealous. For example, in the current master branch:

    Cryptol> (xs:[8][8]) where xs = xs >> 1
    [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]

and in `robdockins-new-eval`:

    Cryptol> (xs:[8][8]) where xs = xs >> 1
    <<loop>> while evaluating (at <interactive>:1:19--1:21, <interactive>::xs)

The evaluator should be able to tell from the type that `xs` is an 8-element sequence.

(To be fair, in master, the same definition with `<<` fails to terminate. A correct evaluator should be able to evaluate both definitions to a list of zeros.)

**Comment by robdockins** [comment]
Following the 2.4.0 release, I think this is now ready to merge.  Provided there are no objections, I intend to merge this later today.

**Pull request merged**
